function writeIntro(name) {
    var description = {}

    description['uefa'] = "<h3>Introduction</h3>" +
        "The UEFA Champions League is an annual continental club football competition " +
        "organised by the Union of European Football Associations (UEFA) and contested " +
        "by top-division European clubs. It is one of the most prestigious tournaments " +
        "in the world and the most prestigious club competition in European football, " +
        "played by the national league champion (and, for some nations, one or more runners-up) " +
        "of each UEFA national association.";

    description['spanish'] = "<h3>La Liga</h3>" +
        "La Liga is the top professional association football " +
        "division of the Spanish football league system."

    description['england'] = "<h3>Premier League</h3>" +
        "The Premier League is an English professional league for men's association football clubs. At the top of the English football league system, it is the country's primary football competition."
//la liga
    description['rma'] = "<h3>Real Madrid Club de Fútbol</h3>" +
        "Founded in 1902 as Madrid Football Club, the team has traditionally worn a white home kit since inception. The word Real is Spanish for Royal and was bestowed to the club by King Alfonso XIII in 1920 together with the royal crown in the emblem. The team has played its home matches in the 85,454-capacity Santiago Bernabéu Stadium in downtown Madrid since 1947. Unlike most European sporting entities, Real Madrid's members (socios) have owned and operated the club throughout its history."

    description['barca'] = "<h3>Futbol Club Barcelona</h3>" +
        "Founded in 1899 by a group of Swiss, English and Catalan footballers led by Joan Gamper, the club has become a symbol of Catalan culture and Catalanism, hence the motto \"Més que un club\" (More than a club). Unlike many other football clubs, the supporters own and operate Barcelona. It is the second most valuable sports team in the world, worth $3.56 billion, and the world's second richest football club in terms of revenue, with an annual turnover of €560.8 million."
	description['atletico'] = "<h3>Club Atlético de Madrid</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['sevilla'] = "<h3>Sevilla Fútbol Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['bilbao'] = "<h3>Athletic Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
 	description['sociedad'] = "<h3>Real Sociedad de Fútbol</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['valencia'] = "<h3>València Club de Futbol</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
//premiere
	description['mancity'] = "<h3>Manchester City Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['chelsea'] = "<h3>Chelsea Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['arsenal'] = "<h3>Arsenal Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['hotspur'] = "<h3>Tottenham Hotspur Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['liverpool'] = "<h3>Liverpool Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['manu'] = "<h3>Manchester United Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['leicester'] = "<h3>Leicester City Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
//bundesliga
	description['bayern'] = "<h3>Club Fußball-Club Bayern München e.V.</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['bvb'] = "<h3>Club Ballspielverein Borussia 09 e.V. Dortmund</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['leverkusen'] = "<h3>Bayer 04 Leverkusen Fußball GmbH</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['wolfsburg'] = "<h3>Verein für Leibesübungen Wolfsburg e. V</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['schalke'] = "<h3>Fußballclub Gelsenkirchen-Schalke 04 e. V</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['monchen'] = "<h3>Borussia VfL 1900 Mönchengladbach e.V.</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
//serie a
	description['juventus'] = "<h3>Juventus Football Club S.p.A.</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['roma'] = "<h3>Associazione Sportiva Roma</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['napoli'] = "<h3>Società Sportiva Calcio Napoli</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['milan'] = "<h3>Associazione Calcio Milan</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
//liga a
	description['psg'] = "<h3>Paris Saint-Germain Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['monaco'] = "<h3>Association Sportive de Monaco Football Club</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['lyon'] = "<h3>Olympique Lyonnais</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['marseille'] = "<h3>Olympique de Marseille</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
//portugal
	description['benfica'] = "<h3>Sport Lisboa e Benfica</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['sporting'] = "<h3>Sporting Clube de Portugal</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
	description['porto'] = "<h3>Futebol Clube do Porto</h3>" +
        "Club Atlético de Madrid, commonly known as Atlético Madrid, or simply as Atlético, is a Spanish professional football club based in Madrid, that plays in La Liga.</br>In terms of UEFA competition titles won, Atlético Madrid is Spain's third most successful club behind Real Madrid and Barcelona. In terms of the number of titles, Atlético Madrid is third most successful club in Spanish football, behind Real Madrid, Barcelona. Atlético have won La Liga on ten occasions, including a league and cup double in 1996; the Copa del Rey on ten occasions; two Supercopas de España and one Copa Eva Duarte; in Europe, they won the European Cup Winners' Cup in 1962, were runners-up in 1963 and 1986, were European Cup runners-up in 1974, 2014 and 2016,[3] won the Europa League in 2010 and in 2012, won the UEFA Super Cup in 2010 and 2012, as well as the 1974 Intercontinental Cup."
		
		
    // render
    document.getElementById('intro').innerHTML = description[name];
}